version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs: 
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}-<< parameters.node-version >>
      - run:
          name: Install packages
          command: npm install --prefer-offline --no-audit --progress=false
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}-<< parameters.node-version >>
          paths: 
            - node_modules
            - package-lock.json 
      - run:
          name: Run test using nodejs << parameters.node-version >>
          command: node test.js

workflows:
  all-test:
    jobs:
      - test: 
          matrix:
            parameters:
              node-version: ['lts', 'current']